### ISSUE TITLE
Error Enabling Voila Extension

### ISSUE THREAD

**Issue by afeiszli** [QuantStack/voila#120]
Hello,

I am trying to set up Voila with my project. I can pip install but then attempt to enable the extension and get the following. Am I doing this incorrectly? If so, can the correct way of enabling the exension please be added to the docs?

Enabling notebook extension voila/nbextension...
      - Validating: problems found:
        - require?  X voila/nbextension

Traceback (most recent call last):

  File "/opt/app-root/bin/jupyter-serverextension", line 11, in <module>
    sys.exit(main())
  File "/opt/app-root/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/app-root/lib/python3.6/site-packages/notebook/serverextensions.py", line 293, in start
    super(ServerExtensionApp, self).start()
  File "/opt/app-root/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/opt/app-root/lib/python3.6/site-packages/notebook/serverextensions.py", line 210, in start
    self.toggle_server_extension_python(arg)
  File "/opt/app-root/lib/python3.6/site-packages/notebook/serverextensions.py", line 199, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/opt/app-root/lib/python3.6/site-packages/notebook/serverextensions.py", line 329, in _get_server_extension_metadata
    raise KeyError(u'The Python module {} does not include any valid server extensions'.format(module))
KeyError: 'The Python module voila does not include any valid server extensions'

**Comment by SylvainCorlay** [comment]
@afeiszli sorry for the late reply. Are you still experiencing this with the latest voila (0.0.13)? We are about to release 0.1.0.

Also, which version of `notebook` are you install.

**Comment by SylvainCorlay** [comment]
Closing as we have changed the voila extension significantly in master.
