### ISSUE TITLE
[SOLVED] TypeError with %matplotlib notebook

### ISSUE THREAD

**Issue by pllim** [QuantStack/voila#124]
We ran into this problem running `voila notebook.ipynb` containing `%matplotlib notebook` incantation:
```
[IPKernelApp] ERROR | Exception in comm_msg for ...
Traceback (most recent call last):
  File ".../ipykernel/comm/manager.py", line 111, in comm_msg
    comm.handle_msg(msg)
  File ".../ipykernel/comm/comm.py", line 159, in handle_msg
    self._msg_callback(msg)
  File ".../matplotlib/backends/backend_nbagg.py", line 219, in on_message
    message = json.loads(message['content']['data'])
  File ".../json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```

Seems to be fixed by changing that incantation to `%matplotlib widget`. Posting here in case others run into the same problem.

**Comment by SylvainCorlay** [comment]
Thanks, closing as solved.

**Comment by darrencl** [comment]
Hi, I am still getting error by using `%matplotlib notebook`, it is different error though. Please find the trace below.

```
ERROR:tornado.application:Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/darren/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/home/darren/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/home/darren/anaconda3/lib/python3.7/site-packages/voila/handler.py", line 58, in get
    result = executenb(notebook, km=km, cwd=cwd)
  File "/home/darren/anaconda3/lib/python3.7/site-packages/voila/execute.py", line 133, in executenb
    return ep.preprocess(nb, resources, km=km)[0]
  File "/home/darren/anaconda3/lib/python3.7/site-packages/voila/execute.py", line 88, in preprocess
    result = super(ExecutePreprocessorWithOutputWidget, self).preprocess(nb, resources=resources, km=km)
  File "/home/darren/anaconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 381, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/darren/anaconda3/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/darren/anaconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 414, in preprocess_cell
    reply, outputs = self.run_cell(cell, cell_index)
  File "/home/darren/anaconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 516, in run_cell
    self.process_message(msg, cell, cell_index)
  File "/home/darren/anaconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 569, in process_message
    self.handle_comm_msg(cell.outputs, msg, cell_index)
  File "/home/darren/anaconda3/lib/python3.7/site-packages/voila/execute.py", line 107, in handle_comm_msg
    state = data['state']
KeyError: 'state'
ERROR:tornado.general:Could not open static file '/base/images/favicon.ico'
ERROR:tornado.general:Could not open static file '/style/style.min.css'

```
Any solutions?

**Comment by SylvainCorlay** [comment]
@darrencl please use `%matplotlib widget` instead of `%matplotlib notebook`. You need ipympl installed.
