### ISSUE TITLE
Dev install cannot find npm

### ISSUE THREAD

**Issue by vidartf** [QuantStack/voila#192]
When trying to run `pip install -e .` on Windows, I get the following error:

```
C:\dev\voila [master ≡ +3 ~3 -0 !]> pip install -e .
Obtaining file:///C:/dev/voila
    Complete output from command python setup.py egg_info:
    running egg_info
    running css
    running jsdeps
    `npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo
    rebuilding js and css failed
    missing files: ['C:\\dev\\voila\\share\\jupyter\\voila\\templates\\default\\static\\voila.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\dev\voila\setup.py", line 290, in <module>
        setup(**setup_args)
      File "C:\Miniconda3\lib\site-packages\setuptools\__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "C:\Miniconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Miniconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Miniconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\dev\voila\setup.py", line 211, in run
        return command.run(self)
      File "C:\dev\voila\setup.py", line 55, in run
        raise e
      File "C:\dev\voila\setup.py", line 48, in run
        self.distribution.run_command('jsdeps')
      File "C:\Miniconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\dev\voila\setup.py", line 128, in run
        raise ValueError(msg)
    ValueError: Missing file: C:\dev\voila\share\jupyter\voila\templates\default\static\voila.js
    npm is required to build a development version

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\dev\voila\
```

**Comment by vidartf** [comment]
Maybe this is relevant: https://github.com/jupyter/jupyter-packaging/blob/master/jupyter_packaging/setupbase.py

**Comment by maartenbreddels** [comment]
@vidartf https://github.com/maartenbreddels/ipyvolume/commit/a434ce71135e95844b1169655fe1d873a2e857a8 should help here, could you try fixing this since you do your dev on windows?

**Comment by vidartf** [comment]
Check the `run` function from `jupyter_packaging` for some tips:

https://github.com/jupyter/jupyter-packaging/blob/15e2da4ed09337d5fb4396c831dfbb8f1b65f59e/jupyter_packaging/setupbase.py#L208-L221

**Comment by vidartf** [comment]
The main two points are probably:
- Supplying command as string vs list.
- Using `shell=True` or not.

**Comment by vidartf** [comment]
I'll do a PR.
