### ISSUE TITLE
Python 2 Support

### ISSUE THREAD

**Issue by dg1sek** [QuantStack/voila#232]
After having installed using 
`pip install voila
`
I get
```
(base) imac:jupyter-notebook dg1sek$ voila Siegfried\'s\ Notebook.ipynb 
[Voila] Using /var/folders/tv/7sz5lrbn1njfn0v5lcszbdd40000gr/T to store connection files
[Voila] Storing connection files in /var/folders/tv/7sz5lrbn1njfn0v5lcszbdd40000gr/T/voila_PGxCjQ.
[Voila] Serving static files from /Users/dg1sek/anaconda2/lib/python2.7/site-packages/voila/static.
Traceback (most recent call last):
  File "/Users/dg1sek/anaconda2/bin/voila", line 10, in <module>
    sys.exit(main())
  File "/Users/dg1sek/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/dg1sek/anaconda2/lib/python2.7/site-packages/voila/app.py", line 452, in start
    self.launch_browser()
  File "/Users/dg1sek/anaconda2/lib/python2.7/site-packages/voila/app.py", line 481, in launch_browser
    with open(fd, 'w', encoding='utf-8') as fh:
TypeError: coercing to Unicode: need string or buffer, int found

```

**Comment by SylvainCorlay** [comment]
Hi @dg1sek thanks for posting.

Voilà is Python 3 only!

**Comment by martinRenou** [comment]
I'm not sure it has to do with the Python version, the CI is passing with Python2.7

**Comment by dg1sek** [comment]
```
pip uninstall voila
pip3 install voila

```
seems to have solved it. Thanks!
