### ISSUE TITLE
jupyter_client.kernelspec.NoSuchKernel: No such kernel

### ISSUE THREAD

**Issue by plynch-chewy** [QuantStack/voila#267]
Created a new conda environment (foo), but voila doesn't seem to find the right kernel? 

Installed with `conda install -c conda-forge voila`

Logs below:

```
(foo) ~/projects/product_images🔥 voila Untitled.ipynb 
[Voila] Using /var/folders/4n/0sp8jh792_j5kylnfw7cg6whkm36s2/T to store connection files
[Voila] Storing connection files in /var/folders/4n/0sp8jh792_j5kylnfw7cg6whkm36s2/T/voila_kdrnd1i1.
[Voila] Serving static files from /Users/plynch/miniconda3/envs/foo/lib/python3.7/site-packages/voila/static.
[Voila] Voila is running at:
http://localhost:8866/
ERROR:tornado.application:Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/plynch/miniconda3/envs/foo/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/Users/plynch/miniconda3/envs/foo/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Users/plynch/miniconda3/envs/foo/lib/python3.7/site-packages/voila/handler.py", line 56, in get
    kernel_id = yield tornado.gen.maybe_future(self.kernel_manager.start_kernel(kernel_name=kernel_name, path=cwd))
  File "/Users/plynch/miniconda3/envs/foo/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/Users/plynch/miniconda3/envs/foo/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Users/plynch/miniconda3/envs/foo/lib/python3.7/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 170, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/Users/plynch/miniconda3/envs/foo/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/Users/plynch/miniconda3/envs/foo/lib/python3.7/site-packages/jupyter_client/manager.py", line 246, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/Users/plynch/miniconda3/envs/foo/lib/python3.7/site-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/Users/plynch/miniconda3/envs/foo/lib/python3.7/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/Users/plynch/miniconda3/envs/foo/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 236, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named conda-env-foo-py
ERROR:tornado.general:Could not open static file '/base/images/favicon.ico'
ERROR:tornado.general:Could not open static file '/style/style.min.css'
```

**Comment by SylvainCorlay** [comment]
Thanks @plynch-chewy for reporting.

Could you please report the content of the kernelspec in the said notebook?

**Comment by plynch-chewy** [comment]
What is the best way to do that?

**Comment by SylvainCorlay** [comment]
> Is this it?

Yes, this is it!

> conda install nb_conda_kernels

Yes, this appears to be an issue with the fact that conda kernels use a custom kernel manager.

At the moment, this is specific to the classic notebook server. We probably need to contribute the change to `nb_conda_kernels` so that it also supports `jupyter_server`.

**Comment by plynch-chewy** [comment]
I got it to work by manually editing the metadata kernelspec name in the ipynb file, then running voila.

A snippet of the end of my notebook file looks like this after the change:
```
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:foo]",
   "language": "python",
   "name": "**python3**"
  },
```

**Comment by plynch-chewy** [comment]
Even though I found a hack, I think it would be helpful to work with `nb_conda_kernels` since that seems a common approach for working with many kernels.

**Comment by aaronlelevier** [comment]
I got this error from launching a Jupyter notebook in a different Python version. Relaunching the notebook in the new Python version updated the notebook metadata, then it just worked.
