### ISSUE TITLE
Report errors when notebook execution fails

### ISSUE THREAD

**Issue by SylvainCorlay** [QuantStack/voila#34]
Currently, this merely results in a 503 error screen.

More details could be made available to the user (optionally since, this could give information about the code being executed).

**Comment by jtpio** [comment]
Having a way to inform the user when the kernel is restarted would also be useful (out of memory for example which can happen after the notebook has been executed).

**Comment by yuvipanda** [comment]
If you have a notebook with code:

```python
raise Exception("hi");
```

When serving it, you get a 503 and the following in the logs:

```
[Voila] Executing notebook with kernel: 
ERROR:tornado.application:Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/yuvipanda/.local/share/virtualenvs/nbresuse-IT4b9ZTA/lib/python3.6/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/home/yuvipanda/.local/share/virtualenvs/nbresuse-IT4b9ZTA/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/home/yuvipanda/.local/share/virtualenvs/nbresuse-IT4b9ZTA/lib/python3.6/site-packages/voila/handler.py", line 66, in get
    result = executenb(notebook, km=km)
  File "/home/yuvipanda/.local/share/virtualenvs/nbresuse-IT4b9ZTA/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 534, in executenb
    return ep.preprocess(nb, resources, km=km)[0]
  File "/home/yuvipanda/.local/share/virtualenvs/nbresuse-IT4b9ZTA/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 354, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/yuvipanda/.local/share/virtualenvs/nbresuse-IT4b9ZTA/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/yuvipanda/.local/share/virtualenvs/nbresuse-IT4b9ZTA/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 378, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
raise Exception("Hi")
------------------

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-e0bfd6b3c1b1> in <module>
----> 1 raise Exception("Hi")

Exception: Hi
Exception: Hi

```

Would be nice to show this to the user, however we have to consider the security implications of showing unfiltered exception info to users. It might leak data that shouldn't be leaked.

**Comment by maartenbreddels** [comment]
Solved in https://github.com/QuantStack/voila/pull/186
