### ISSUE TITLE
Cannot start conda kernel error

### ISSUE THREAD

**Issue by scottlittle** [QuantStack/voila#45]
[This notebook](https://github.com/scottlittle/binder/blob/master/network%20plot%20-%20les%20mis%20-%20update.ipynb) works in appmode, but I think voila is not able to start the custom conda env kernel:
```
(pythreejs_env) MacBook-Pro:examples scott$ voila network\ plot\ -\ les\ mis\ -\ update.ipynb 
[Voila] Storing connection files in /var/folders/m0/zs_gtkld71bb06pqswcsndv00000gn/T/voila_65hjawfv.
[Voila] Serving static files from /Users/scott/miniconda3/envs/pythreejs_env/lib/python3.6/site-packages/voila/static.
[Voila] Voila listening on port 8866.
ERROR:tornado.application:Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/scott/miniconda3/envs/pythreejs_env/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/Users/scott/miniconda3/envs/pythreejs_env/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/scott/miniconda3/envs/pythreejs_env/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/scott/miniconda3/envs/pythreejs_env/lib/python3.6/site-packages/voila/handler.py", line 47, in get
    kernel_id = yield tornado.gen.maybe_future(self.kernel_manager.start_kernel(kernel_name=kernel_name))
  File "/Users/scott/miniconda3/envs/pythreejs_env/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/scott/miniconda3/envs/pythreejs_env/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/scott/miniconda3/envs/pythreejs_env/lib/python3.6/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/Users/scott/miniconda3/envs/pythreejs_env/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/Users/scott/miniconda3/envs/pythreejs_env/lib/python3.6/site-packages/jupyter_client/manager.py", line 246, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/Users/scott/miniconda3/envs/pythreejs_env/lib/python3.6/site-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/Users/scott/miniconda3/envs/pythreejs_env/lib/python3.6/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/Users/scott/miniconda3/envs/pythreejs_env/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 236, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named conda-env-pythreejs_env-py
ERROR:tornado.general:Could not open static file '/base/images/favicon.ico'
ERROR:tornado.general:Could not open static file '/style/style.min.css'
ERROR:tornado.access:500 GET / (::1) 359.25ms
```

**Comment by scottlittle** [comment]
Had same problem with a similar notebook and solved by using only the default conda environment.  I am using Python 3.7 for all of my environments.

**Comment by maartenbreddels** [comment]
Hi Scott,

would you say there (still) is a bug in voila, or was this a user error? This to me looks like using a kernel that was not available from your environment. (Note that conda's root env 'leaks' binaries from the root environment to others. For instance, maybe you started voila from the root env, a better way could be `python -m voila ....`.

cheers,

Maarten

**Comment by scottlittle** [comment]
Yes, I believe it was the name of the kernel.  I recently changed the kernel name in the ipynb file and it worked.

**Comment by SylvainCorlay** [comment]
Thankz! Closing the issue then.
