### ISSUE TITLE
Windows 10: 500 Internal Server Error

### ISSUE THREAD

**Issue by pllim** [QuantStack/voila#98]
Does this work on Windows 10? I installed `voila` from `conda-forge` and tried running
```
voila voilable_astrowidgets.ipynb
```
where the notebook is at https://github.com/spacetelescope/dat_pyinthesky/blob/master/jupyter_platform/voilable_astrowidgets.ipynb and I get "500 Internal Server Error" when I open up http://localhost:8866/ on my browser (Chrome) with the following traceback
```
VOILA: 16368
[Voila] Using C:\...\AppData\Local\Temp to store connection files
[Voila] Storing connection files in C:\...\AppData\Local\Temp\voila_rz22_17q.
[Voila] Serving static files from C:\...\Miniconda3\envs\py37\lib\site-packages\voila\static.
[Voila] Voila listening on port 8866.
[18780:12268:0404/134334.485:ERROR:cache_util_win.cc(19)] Unable to move the cache: 0
[18780:12268:0404/134334.486:ERROR:cache_util.cc(140)] Unable to move cache folder C:\...\AppData\Local\Google\Chrome\User Data\ShaderCache\GPUCache to C:\...\AppData\Local\Google\Chrome\User Data\ShaderCache\old_GPUCache_000
[18780:12268:0404/134334.486:ERROR:disk_cache.cc(184)] Unable to create cache
[18780:12268:0404/134334.486:ERROR:shader_disk_cache.cc(622)] Shader Cache Creation failed: -2
[Voila] WARNING | Notebook voilable_astrowidgets.ipynb is not trusted
Opening in existing browser session.
ERROR:tornado.application:Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\voila\handler.py", line 64, in get
    kernel_id = yield tornado.gen.maybe_future(self.kernel_manager.start_kernel(kernel_name=kernel_name))
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 170, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\jupyter_client\manager.py", line 246, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\jupyter_client\manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\jupyter_client\manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\jupyter_client\kernelspec.py", line 236, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named astro36
ERROR:tornado.general:Could not open static file 'C:\\base\\images\\favicon.ico'
ERROR:tornado.general:Could not open static file 'C:\\style\\style.min.css'
ERROR:tornado.access:500 GET / (::1) 134.71ms
```

**Comment by pllim** [comment]
I think that error was for something in the notebook that is unrelated to this package internals. Sorry for the noise.

**Comment by pllim** [comment]
UPDATE: Reopening since I still get the same error after fixing another error in the notebook.

**Comment by maartenbreddels** [comment]
> jupyter_client.kernelspec.NoSuchKernel: No such kernel named astro36

This means voila cannot find a kernel with that name, maybe change the name, or even remove it from the notebook.

**Comment by pllim** [comment]
Yes, deleting the hidden metadata field fixed this. Thanks!
